# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   brew install postgresql
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dyssekilde_dk_development

test:
  <<: *default
  database: dyssekilde_dk_test

production:
  primary: &primary_production
    <<: *default
    database: dyssekilde_dk_production
    username: dyssekilde_dk
    password: <%= ENV["DYSSEKILDE_DK_DATABASE_PASSWORD"] %>
    host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  cache:
    <<: *primary_production
    database: dyssekilde_dk_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: dyssekilde_dk_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: dyssekilde_dk_production_cable
    migrations_paths: db/cable_migrate
